### ISSUE TITLE
Please support all browser sizes

### ISSUE THREAD

**Issue by utako** [wendorf/isiticecreamyet#3]
Also I would appreciate it if you made this mobile friendly. Thanks

**Comment by wendorf** [comment]
Hi @utako ,

Thanks for your feedback. A well-written feature request usually documents some use cases, discusses potential priority of the work, and includes necessary details such as 1) which mobile devices to support or, at least, 2) some data that can be used to help guide that decision.

Unfortunately, due to the lack of detail, I will be unable to fulfill this request. ...at least your request was mobile friendly!

![bird](http://i.giphy.com/xT77XLWNWgg42wbKVi.gif)
